/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Content;
import java.text.DecimalFormat;
import model.BarangElektronik;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import model.DataCollection;
import model.Handphone;
import model.Laptop;
import model.TV;
/**
 *
 * @author RadityaaR
 */
public class Content extends javax.swing.JPanel {

    /**
     * Creates new form Content
     */
    public Content() {
        initComponents();
        DataCollection.daftarBarang.add(new Laptop("ROG Zephyrus", "Asus", 25000000, 10, "Intel i9", "RTX 3080", 32));
            DataCollection.daftarBarang.add(new Laptop("Macbook Pro", "Appel", 18000000, 20, "Mac OS98", "RTX 3080", 32));
            DataCollection.daftarBarang.add(new Laptop("Lenovo LOQ", "Lenovo", 14000000, 8, "Ryzen ", "RTX 3080", 32));
            DataCollection.daftarBarang.add(new Handphone("Galaxy S23", "Samsung", 15000000, 15, 5000, 108, true));
            DataCollection.daftarBarang.add(new Handphone("Iphone 15 Pro Max", "Apple", 15000000, 10, 5000, 108, true));
            DataCollection.daftarBarang.add(new Handphone("Pixel 9", "Google", 13000000, 5, 5000, 108, true));
            DataCollection.daftarBarang.add(new TV("Smart OLED", "LG", 12000000, 8, 55.0, "OLED", "4K"));
        tampilkanDaftarBarang(DataCollection.daftarBarang);
    }
    
    public void tampilkanDaftarBarang(List<BarangElektronik> daftarProduk) {
    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    model.setRowCount(0); // clear table sebelum diisi ulang
    DecimalFormat formatRupiah = new DecimalFormat("Rp #,###");

    for (BarangElektronik p : daftarProduk) {
        Object[] row = {
            p.getNamaBarang(),
            p.getMerk(),
            formatRupiah.format(p.getHarga()),
            p.getStok()
        };
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnRefreshBarang = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR BARANG TECHUB");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Merk", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable3);

        btnRefreshBarang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRefreshBarang.setText("Refresh");
        btnRefreshBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefreshBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(btnRefreshBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshBarangActionPerformed
        tampilkanDaftarBarang(DataCollection.daftarBarang);
    }//GEN-LAST:event_btnRefreshBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
