/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Content;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author RadityaaR
 */
public class SecondPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecondPanel
     */
    public SecondPanel() {
        initComponents();
        for (model.BarangElektronik b : model.DataCollection.daftarBarang) {
            comboBarang.addItem(b.getNamaBarang() + " - " + b.getMerk());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        formPembeli = new javax.swing.JPanel();
        formPembelitxt = new javax.swing.JLabel();
        namatxt = new javax.swing.JLabel();
        alamattxt = new javax.swing.JLabel();
        nomorhptxt = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNoHp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        formPembelitxt1 = new javax.swing.JLabel();
        radioKartuKredit = new javax.swing.JRadioButton();
        radioTransferBank = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNamaKartu = new javax.swing.JTextField();
        tfNomorKartu = new javax.swing.JTextField();
        tfNamaBank = new javax.swing.JTextField();
        tfNomorRekening = new javax.swing.JTextField();
        btnBeli = new javax.swing.JButton();
        comboBarang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textHasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Poppins ExtraBold", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Detail Transaksi");
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPembeli.setBackground(new java.awt.Color(255, 255, 255));

        formPembelitxt.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        formPembelitxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formPembelitxt.setText("Form Pembeli");

        namatxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namatxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namatxt.setText("Nama      :");

        alamattxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        alamattxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alamattxt.setText("Alamat   :");

        nomorhptxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        nomorhptxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomorhptxt.setText("No. HP      : ");

        tfNama.setText("Masukkan Nama");

        tfAlamat.setText("Masukkan Alamat");
        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        tfNoHp.setText("Masukkan Nomorr HP");

        javax.swing.GroupLayout formPembeliLayout = new javax.swing.GroupLayout(formPembeli);
        formPembeli.setLayout(formPembeliLayout);
        formPembeliLayout.setHorizontalGroup(
            formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPembeliLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(alamattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAlamat))
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(nomorhptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNoHp))
                    .addComponent(formPembelitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        formPembeliLayout.setVerticalGroup(
            formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPembeliLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(formPembelitxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namatxt)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamattxt)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorhptxt)
                    .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(formPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 400, 130));

        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, -1));

        formPembelitxt1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        formPembelitxt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formPembelitxt1.setText("Pilih Barang");
        add(formPembelitxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, -1));

        buttonGroup1.add(radioKartuKredit);
        radioKartuKredit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        radioKartuKredit.setText("Kartu Kredit");
        radioKartuKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKartuKreditActionPerformed(evt);
            }
        });
        add(radioKartuKredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        buttonGroup1.add(radioTransferBank);
        radioTransferBank.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        radioTransferBank.setText("Transfer Bank");
        radioTransferBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTransferBankActionPerformed(evt);
            }
        });
        add(radioTransferBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel1.setText("Nama Pemilik  :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 100, -1));

        jLabel2.setText("No. Kartu         : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel3.setText("Nama Bank :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel4.setText("No. Rekening :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        tfNamaKartu.setText("Masukkan Nama");
        tfNamaKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaKartuActionPerformed(evt);
            }
        });
        add(tfNamaKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, -1));

        tfNomorKartu.setText("Masukkan Nomor");
        add(tfNomorKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 220, -1));

        tfNamaBank.setText("Masukkan Nama Bank");
        add(tfNamaBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 220, -1));

        tfNomorRekening.setText("Masukkan Nomor Rekening");
        tfNomorRekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomorRekeningActionPerformed(evt);
            }
        });
        add(tfNomorRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 220, -1));

        btnBeli.setBackground(new java.awt.Color(255, 51, 51));
        btnBeli.setFont(new java.awt.Font("Poppins Black", 1, 14)); // NOI18N
        btnBeli.setForeground(new java.awt.Color(255, 255, 255));
        btnBeli.setText("Checkout");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        add(btnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 120, 70));

        comboBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBarangActionPerformed(evt);
            }
        });
        add(comboBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        jLabel5.setText("Nama Barang");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        tfJumlah.setText("Kuantitas");
        add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, 30));

        jLabel6.setText("Jumlah Beli");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        textHasil.setColumns(20);
        textHasil.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        textHasil.setRows(5);
        jScrollPane2.setViewportView(textHasil);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 640, 210));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setText("Detail Transaksi");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void radioKartuKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKartuKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioKartuKreditActionPerformed

    private void radioTransferBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTransferBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTransferBankActionPerformed

    private void tfNamaKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaKartuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaKartuActionPerformed

    private void tfNomorRekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomorRekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomorRekeningActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        try {
            // 1. Ambil data pembeli
            String nama = tfNama.getText();
            String alamat = tfAlamat.getText();
            String noHp = tfNoHp.getText();

            // Validasi input dasar
            if (nama.isEmpty() || alamat.isEmpty() || noHp.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mohon isi semua data pembeli.");
                return;
            }

            // 2. Ambil jumlah beli
            int jumlah = Integer.parseInt(tfJumlah.getText());

            // 3. Ambil barang yang dipilih dari combo box
            int indexBarang = comboBarang.getSelectedIndex();
            
            if (indexBarang < 0) {
                JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu.");
                return;
            }
            
            model.BarangElektronik barang = model.DataCollection.daftarBarang.get(indexBarang);
            if (jumlah > barang.getStok()) {
            JOptionPane.showMessageDialog(this, "Stok barang tidak mencukupi.");
            return;
}

            // 4. Buat objek Pembeli
            model.Pembeli pembeli = new model.Pembeli(nama, alamat, noHp);

            // 5. Tentukan metode pembayaran dari radio button
            model.Pembayaran pembayaran;
            if (radioKartuKredit.isSelected()) {
                String namaKartu = tfNamaKartu.getText();
                String noKartu = tfNomorKartu.getText();
                if (namaKartu.isEmpty() || noKartu.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Isi nama pemilik dan nomor kartu kredit.");
                    return;
                }
                pembayaran = new model.KartuKredit(namaKartu, noKartu);
            } else if (radioTransferBank.isSelected()) {
                String namaBank = tfNamaBank.getText();
                String noRek = tfNomorRekening.getText();
                if (namaBank.isEmpty() || noRek.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Isi nama bank dan nomor rekening.");
                    return;
                }
                pembayaran = new model.TransferBank(namaBank, noRek);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih metode pembayaran.");
                return;
            }

            // 6. Buat transaksi
            String idTransaksi = "TRX" + (model.FileOperation.hitungTransaksiDalamFile() + 1);
            model.Transaksi trx = new model.Transaksi(idTransaksi, pembeli, barang, jumlah, pembayaran);

            // 7. Proses transaksi
            trx.prosesTransaksi();

            // 8. Tampilkan hasil transaksi
            String hasil = trx.cetakDetailTransaksi();
            textHasil.setText(hasil);

            // 9. Simpan ke file
            model.FileOperation.writeToFile(hasil);

            JOptionPane.showMessageDialog(this, "Transaksi berhasil diproses!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka.");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnBeliActionPerformed

    private void comboBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamattxt;
    private javax.swing.JButton btnBeli;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBarang;
    private javax.swing.JPanel formPembeli;
    private javax.swing.JLabel formPembelitxt;
    private javax.swing.JLabel formPembelitxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel namatxt;
    private javax.swing.JLabel nomorhptxt;
    private javax.swing.JRadioButton radioKartuKredit;
    private javax.swing.JRadioButton radioTransferBank;
    private javax.swing.JTextArea textHasil;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNamaBank;
    private javax.swing.JTextField tfNamaKartu;
    private javax.swing.JTextField tfNoHp;
    private javax.swing.JTextField tfNomorKartu;
    private javax.swing.JTextField tfNomorRekening;
    // End of variables declaration//GEN-END:variables
}
