/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Content;

/**
 *
 * @author RadityaaR
 */
public class SecondPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecondPanel
     */
    public SecondPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formPembeli = new javax.swing.JPanel();
        formPembelitxt = new javax.swing.JLabel();
        namatxt = new javax.swing.JLabel();
        alamattxt = new javax.swing.JLabel();
        nomorhptxt = new javax.swing.JLabel();
        namatxtfield = new javax.swing.JTextField();
        alamattxtfield = new javax.swing.JTextField();
        nomorhptxtfield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        formPembelitxt1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        buttonPembayaran = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPembeli.setBackground(new java.awt.Color(255, 255, 255));

        formPembelitxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        formPembelitxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formPembelitxt.setText("Form Pembeli");

        namatxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namatxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namatxt.setText("Nama      :");

        alamattxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        alamattxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alamattxt.setText("Alamat   :");

        nomorhptxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        nomorhptxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomorhptxt.setText("No. HP      : ");

        namatxtfield.setText("Masukkan Nama");

        alamattxtfield.setText("Masukkan Alamat");
        alamattxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamattxtfieldActionPerformed(evt);
            }
        });

        nomorhptxtfield.setText("Masukkan Nomorr HP");

        javax.swing.GroupLayout formPembeliLayout = new javax.swing.GroupLayout(formPembeli);
        formPembeli.setLayout(formPembeliLayout);
        formPembeliLayout.setHorizontalGroup(
            formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPembeliLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formPembelitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namatxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(alamattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamattxtfield))
                    .addGroup(formPembeliLayout.createSequentialGroup()
                        .addComponent(nomorhptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorhptxtfield)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        formPembeliLayout.setVerticalGroup(
            formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPembeliLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(formPembelitxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namatxt)
                    .addComponent(namatxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamattxt)
                    .addComponent(alamattxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorhptxt)
                    .addComponent(nomorhptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(formPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, -1));

        formPembelitxt1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        formPembelitxt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formPembelitxt1.setText("Pilih Barang");
        add(formPembelitxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 370, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Jumlah Beli", "Checkout"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, 70));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jRadioButton1.setText("Kartu Kredit");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jRadioButton2.setText("Transfer Bank");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel1.setText("Nama Pemilik  :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, -1));

        jLabel2.setText("No. Kartu         : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setText("Nama Bank :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel4.setText("No. Rekening :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jTextField1.setText("Masukkan Nama");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, -1));

        jTextField2.setText("Masukkan Nomor");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        jTextField3.setText("Masukkan Nama Bank");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 220, -1));

        jTextField4.setText("Masukkan Nomor Rekening");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 220, -1));

        buttonPembayaran.setText("Lanjutkan ke Detail Pembayaran");
        buttonPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPembayaranActionPerformed(evt);
            }
        });
        add(buttonPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void alamattxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamattxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamattxtfieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void buttonPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPembayaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamattxt;
    private javax.swing.JTextField alamattxtfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPembayaran;
    private javax.swing.JPanel formPembeli;
    private javax.swing.JLabel formPembelitxt;
    private javax.swing.JLabel formPembelitxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel namatxt;
    private javax.swing.JTextField namatxtfield;
    private javax.swing.JLabel nomorhptxt;
    private javax.swing.JTextField nomorhptxtfield;
    // End of variables declaration//GEN-END:variables
}
